pecipes_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipesapp.urls', namespace='recipesapp')),
    path('__debug__', include('debug_toolbar.urls')),
]

recipesapp/urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls.static import static

app_name = 'recipesapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipe/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('recipe/add/', views.add_recipe, name='add_recipe'),
    path('recipe/edit/<int:recipe_id>/', views.edit_recipe, name='edit_recipe'),
    path('recipe/del/<int:recipe_id>/', views.delete_recipe, name='delete_recipe'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipesapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Recipe(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    instructions = models.TextField()
    preparation_time = models.PositiveIntegerField() 
    image = models.ImageField(upload_to='static/img/')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recipes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=100)
   
    def __str__(self):
        return self.name

class RecipeCategoryRelationship(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)    

    class Meta:
        unique_together = ['recipe', 'category']  

recipesapp/forms.py
from django import forms
from .models import Recipe, Category, RecipeCategoryRelationship

class RecipeForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=True)

    class Meta:
        model = Recipe
        fields = ['title', 'description', 'instructions', 'preparation_time', 'image', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'instructions': forms.Textarea(attrs={'class': 'form-control'}),
            'preparation_time': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'title': 'Название',
            'description': 'Описание',
            'instructions': 'Инструкции',
            'preparation_time': 'Время приготовления (в минутах)',
            'image': 'Изображение',
            'category': 'Категория',
        }

recipesapp/views.py
import os
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout,authenticate
from .forms import RecipeForm
from .models import Recipe,RecipeCategoryRelationship,Category
from django.contrib.auth.decorators import login_required
from django.contrib import messages 
from datetime import datetime


def home(request):
    categories = Category.objects.all()
    recipe_relationships = RecipeCategoryRelationship.objects.all().order_by('-id')[:5]
    return render(request, 'recipesapp/home.html', {'categories': categories, 'recipe_relationships': recipe_relationships})

def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    return render(request, 'recipesapp/recipe_detail.html', {'recipe': recipe})

#Авторизация
def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Добро пожаловать, {username}!')
                return redirect('recipesapp:home')
            else:
                messages.error(request, 'Некорректные логин или пароль.')
    else:
        form = AuthenticationForm()
    return render(request, 'recipesapp/login.html', {'form': form})

#Разлогинивание
def user_logout(request):
    logout(request)
    return redirect('recipesapp:home')

#Регистрация
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Аккаунт создан для {username}!')
            return redirect('recipesapp:login')
    else:
        form = UserCreationForm()
    return render(request, 'recipesapp/register.html', {'form': form})

#Создание рецепта
@login_required(login_url='/accounts/login/')  
def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.image = request.FILES['image']
            
            current_time = datetime.now().strftime("%Y%m%d%H%M%S%f")
            file_extension = recipe.image.name.split('.')[-1]
            file_name = f"{current_time}.{file_extension}"
            recipe.image.name = file_name
            recipe.save()

            category_id = request.POST.get('category')
            category = Category.objects.get(pk=category_id)
            RecipeCategoryRelationship.objects.create(recipe=recipe, category=category)            
            return redirect('recipesapp:home')
    else: 
        form = RecipeForm()
    return render(request, 'recipesapp/add_recipe.html', {'form': form})    

#Редактирование рецепта
def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    recipe_category_relationship = RecipeCategoryRelationship.objects.filter(recipe=recipe).first()
    previous_category = None

    if recipe_category_relationship:
        previous_category = recipe_category_relationship.category

    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            
            if 'image' in request.FILES:
                recipe.image = request.FILES['image']
                current_time = datetime.now().strftime("%Y%m%d%H%M%S%f")
                file_extension = recipe.image.name.split('.')[-1]
                file_name = f"{current_time}.{file_extension}"
                recipe.image.name = file_name

            recipe.save()

            category_id = request.POST.get('category')
            if category_id:
                category = Category.objects.get(pk=category_id)
            else:
                category = previous_category

            if recipe_category_relationship:
                recipe_category_relationship.category = category
                recipe_category_relationship.save()
            else:
                RecipeCategoryRelationship.objects.create(recipe=recipe, category=category)

            return redirect('recipesapp:home')
    else:
        form = RecipeForm(instance=recipe)
    
    return render(request, 'recipesapp/edit_recipe.html', {'form': form})

# Удаление рецепта
# def delete_recipe(request, recipe_id):
#     recipe = get_object_or_404(Recipe, id=recipe_id)
#     recipe.delete()
#     return redirect('recipesapp:home')

def delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    
    # Удаление файла из папки recipe_image
    if recipe.image:
        image_path = recipe.image.path
        if os.path.exists(image_path):
            os.remove(image_path)
    
    recipe.delete()
    
    return redirect('recipesapp:home')

recipesapp/templates/recipesapp/add_recipe.html
{% extends 'recipesapp/base.html' %}

{% block title %}Добавить рецепт{% endblock %}

{% block content %}
    <div class="container">
        <h2>Добавить рецепт</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>
{% endblock %}

recipesapp/templates/recipesapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Рецепты{% endblock %}</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/my.css' %}">

</head>
<body>
    <header class="bg-dark text-white">
        <div class="container">
            <h1 class="my-4">Рецепты</h1>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recipesapp:home' %}">Главная</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recipesapp:add_recipe' %}">Добавить рецепт</a>
                    </li>
                {% endif %}                
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'recipesapp:logout' %}">Выйти</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'recipesapp:login' %}">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'recipesapp:register' %}">Регистрация</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>

    <main class="container mt-4">
        {% block content %}
        {% endblock %}
    </main>
    
    <footer class="bg-dark text-white py-3 mt-3">
        <div class="container">
            <p class="m-0">&copy; 2024 Мои рецепты</p>
        </div>
    </footer>
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

recipesapp/templates/recipesapp/edit_recipe.html
{% extends 'recipesapp/base.html' %}

{% block title %}Редактировать рецепт{% endblock %}

{% block content %}
    <div class="container">
        <h2>Добавить рецепт</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
            </div>
            {% endfor %}
            <p><b>ВНИМАНИЕ!!!</b> Не забудьте выбрать категорию, к сожалению, функция сохранения старой категории находится в разрвботке</p>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
{% endblock %}

recipesapp/templates/recipesapp/home.html
{% extends 'recipesapp/base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}    
    {% for category in categories %}        
        <ul class="list-group">
            {% for recipe in recipe_relationships %}
                {% if recipe.category == category %}
                    <li class="list-group-item"><a href="{% url 'recipesapp:recipe_detail' recipe.recipe.id %}">{{ recipe.recipe.title }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endfor %}    
{% endblock %}

recipesapp/templates/recipesapp/login.html
{% extends 'recipesapp/base.html' %}

{% block title %}Войти{% endblock %}

{% block content %}
    <h2>Войти</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
    </form>
{% endblock %}

recipesapp/templates/recipesapp/recipe_detail.html
{% extends 'recipesapp/base.html' %}

{% block title %}{{ recipe.title }}{% endblock %}

{% block content %}
<div class="recipe">
    <div class="image">
        {% if recipe.image %}
        <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="img-fluid image_img">
        {% endif %}
    </div>
    <div class="content">
        <h2>{{ recipe.title }}</h2>
        <p>Описание: {{ recipe.description }}</p>
        <p>Время приготовления: {{ recipe.preparation_time }} minutes</p>
        {% if user.is_authenticated and user == recipe.author %}
            <a href="{% url 'recipesapp:edit_recipe' recipe.id %}" class="btn btn-primary mt-3">Редактировать</a>
            <a href="{% url 'recipesapp:delete_recipe' recipe.id %}" class="btn btn-primary mt-3">Удалить</a>
        {% endif %}
    </div>
</div>


{% endblock %}

recipesapp/templates/recipesapp/register.html
{% extends 'recipesapp/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <h2>Регистрация</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
    </form>
{% endblock %}